name: My first pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4 
      - name: build image
        run:  docker build -t ekajane83/ciportfolio .
      - name: List imges
        run:  docker images
        
        
  


